kind: Pod
apiVersion: v1
metadata:
  name: myenvsecret

spec:
  containers:
   - name: c1
     image: ubuntu
     command: ["/bin/bash", "-c", "while true; do echo Hello env-secret; sleep 3; done"]  

     env:
      - name: MYENVUSER           # Environment variable for username
        valueFrom:
          secretKeyRef:
            name: mytestsecrets   # secrets from tmpf file
            key: username.txt     # store secret data

      - name: MYPASSWORD
        valueFrom:
          secretKeyRef:
            name: mytestsecrets
            key: password.txt      
