kind: Pod
apiVersion: v1
metadata:
  name: myvolsecret

spec:
  containers:
   - name: c1
     image: ubuntu
     command: ["/bin/bash", "-c", "while true; do echo Hello secrets file; sleep 3; done"] 


     volumeMounts:
      - name: testsecret
        mountPath: "/tmp/mysecret"

  volumes:
   - name: testsecret
     secret:
       secretName: mytestsecrets   
