kind: Pod
apiVersion: v1
metadata:
  name: mypod2

spec:
  containers:
   - name: c02
     image: ubuntu
     command: ["/bin/bash", "-c", "while true; do echo Hey Namespace - tester; sleep 5; done"]

